"""eslahe database

Revision ID: 16c9fcafbcb3
Revises: 5570eab8b749
Create Date: 2026-09-29 09:26:57.598981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c9fcafbcb3'
down_revision: Union[str, Sequence[str], None] = '5570eab8b749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tblUsers_email'), table_name='tblUsers')
    op.create_index(op.f('ix_tblUsers_email'), 'tblUsers', ['email'], unique=False)
    op.drop_index(op.f('ix_tblUsers_phone_number'), table_name='tblUsers')
    op.create_index(op.f('ix_tblUsers_phone_number'), 'tblUsers', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tblUsers_phone_number'), table_name='tblUsers')
    op.create_index(op.f('ix_tblUsers_phone_number'), 'tblUsers', ['phone_number'], unique=True)
    op.drop_index(op.f('ix_tblUsers_email'), table_name='tblUsers')
    op.create_index(op.f('ix_tblUsers_email'), 'tblUsers', ['email'], unique=True)
    # ### end Alembic commands ###
