"""create tables

Revision ID: 5570eab8b749
Revises: 
Create Date: 2026-09-28 15:22:07.601563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5570eab8b749'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tblCategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['tblCategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tblCategory_id'), 'tblCategory', ['id'], unique=False)
    op.create_table('tblUsers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'USER', 'GUEST', name='enuserrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_profile_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tblUsers_email'), 'tblUsers', ['email'], unique=True)
    op.create_index(op.f('ix_tblUsers_id'), 'tblUsers', ['id'], unique=False)
    op.create_index(op.f('ix_tblUsers_is_delete'), 'tblUsers', ['is_delete'], unique=False)
    op.create_index(op.f('ix_tblUsers_phone_number'), 'tblUsers', ['phone_number'], unique=True)
    op.create_index(op.f('ix_tblUsers_username'), 'tblUsers', ['username'], unique=True)
    op.create_table('tblProfiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_url', sa.String(length=250), nullable=True),
    sa.Column('national_id', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='engender'), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_fk'], ['tblUsers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('user_id_fk')
    )
    op.create_index(op.f('ix_tblProfiles_id'), 'tblProfiles', ['id'], unique=False)
    op.create_table('tblTasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('grading', sa.Enum('low', 'medium', 'high', name='entaskgrading'), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=True),
    sa.Column('category_id_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id_fk'], ['tblCategory.id'], ),
    sa.ForeignKeyConstraint(['user_id_fk'], ['tblUsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tblTasks')
    op.drop_index(op.f('ix_tblProfiles_id'), table_name='tblProfiles')
    op.drop_table('tblProfiles')
    op.drop_index(op.f('ix_tblUsers_username'), table_name='tblUsers')
    op.drop_index(op.f('ix_tblUsers_phone_number'), table_name='tblUsers')
    op.drop_index(op.f('ix_tblUsers_is_delete'), table_name='tblUsers')
    op.drop_index(op.f('ix_tblUsers_id'), table_name='tblUsers')
    op.drop_index(op.f('ix_tblUsers_email'), table_name='tblUsers')
    op.drop_table('tblUsers')
    op.drop_index(op.f('ix_tblCategory_id'), table_name='tblCategory')
    op.drop_table('tblCategory')
    # ### end Alembic commands ###
