"""create the is_system column for tblCategory, because add the  uncategorized record in table and cannot deleted the this record by users

Revision ID: e65b1fcff8de
Revises: 16c9fcafbcb3
Create Date: 2026-10-01 10:43:50.598537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65b1fcff8de'
down_revision: Union[str, Sequence[str], None] = '16c9fcafbcb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tblCategory', sa.Column('is_system', sa.Boolean(), nullable=False,server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tblCategory', 'is_system')
    # ### end Alembic commands ###
